# Generated by Django 4.0.2 on 2022-02-06 20:55

import Petstagram.main.validators.name_validator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='first_name',
            field=models.CharField(max_length=30, validators=[
                Petstagram.main.validators.name_validator.NameValidator(2, 30, 'first_name')]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(max_length=30, validators=[
                Petstagram.main.validators.name_validator.NameValidator(2, 30, 'second_name')]),
        ),
    ]
