# Generated by Django 4.0.2 on 2022-02-07 20:26

import Petstagram.main.validators.image_size_validator
import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_petmodel_date_alter_profilemodel_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='', validators=[Petstagram.main.validators.image_size_validator.ValidateImage(5)])),
                ('tagged_pets', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(verbose_name=models.CharField(max_length=30)), size=None)),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField()),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 22, 26, 27, 139349)),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 22, 26, 27, 138849)),
        ),
    ]
