# Generated by Django 4.0.2 on 2022-02-06 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_petmodel_date_alter_profilemodel_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 0, 44, 27, 615553)),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 0, 44, 27, 614554)),
        ),
    ]
