# Generated by Django 4.0.2 on 2022-02-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_petimage_alter_petmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
