# Generated by Django 4.0.2 on 2022-02-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_petimage_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='petimage',
            name='pet_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.petmodel'),
        ),
    ]
