# Generated by Django 4.0.2 on 2022-02-09 19:16

import Petstagram.main.validators.name_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_petimage_pet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='first_name',
            field=models.CharField(max_length=2, validators=[Petstagram.main.validators.name_validator.NameValidator(2, 30, 'first_name')]),
        ),
    ]
