# Generated by Django 4.0.2 on 2022-02-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_profilemodel_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='date_of_birth',
            field=models.DateTimeField(default=''),
        ),
    ]
