# Generated by Django 4.0.2 on 2022-02-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_profilemodel_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
