# Generated by Django 4.0.2 on 2022-02-09 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_profilemodel_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='gender',
            field=models.TextField(blank=True, choices=[('Male', 'MALE'), ('Female', 'Female'), ('Do not show', 'Do not show')], null=True),
        ),
    ]
