# Generated by Django 4.0.2 on 2022-02-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_profilemodel_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petimage',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
