# Generated by Django 4.0.2 on 2022-02-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_petimage_pet_id_alter_petimage_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petmodel',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
