# Generated by Django 4.0.2 on 2022-02-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_petmodel_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='petmodel',
            name='likes',
        ),
    ]
