# Generated by Django 4.0.2 on 2022-02-10 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_petmodel_description_remove_petmodel_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='petmodel',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.profilemodel'),
        ),
    ]
